version: "3"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
    shm_size: 1gb
    ports:
      - "${DB_PORT:-5432}:5432"
      # command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - ./data/db:/var/lib/postgresql/data
