version: "3"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
    networks:
      - d9-indexer
    shm_size: 1gb
    ports:
      - "${DB_PORT:-5432}:5432"
      # command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - ./data/db:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DB_NAME=squid
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS=${DB_PASS:-postgres}
      - GQL_PORT=4350
    networks:
      - d9-indexer
    ports:
      - "4350:4350"
    command: ["sqd", "serve:prod"]
  
  processor:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DB_NAME=squid
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS=${DB_PASS:-postgres}
      - RPC_ENDPOINT=${ENDPOINT}
      - CONTRACT_CROSS_CHAIN=vNNoHwVH8af77P4s1ch14yTy7UTd8w9g2VfYA5fBExZzA7i
      - CONTRACT_MARKET_MAKER=z8keEeLwjZFK5NS5PF6xYwTHEbm7jwpH4gBYB1JV6pDTtWg
      - CONTRACT_D9_USDT=uLj9DRUujbpCyK7USZY5ebGbxdtKoWvdRvGyyUsoLWDsNng
      - CONTRACT_MERCHANT=xjyLYnZBRhYYjUKjCp8UiHnmcjHmkPfRSBxTiLLMoEwtzwp
      - CONTRACT_BURN_MANAGER=wRGYShktZsxtKwXCCzqtLW7P1a5K2qDsaXEcRWxVYKGwH7d
      - CONTRACT_NODE_REWARD=xqDsmMNZsCprGkjG6JPCQYysvdBs5GvudLzkXt73BbysX6D
    networks:
      - d9-indexer
    ports:
      - "3000:3000"
    command: ["sqd", "process:prod"]

networks:
  d9-indexer:
